//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.posts = new HashSet<Post>();
        }
    
        public int id_category { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Post> posts { get; set; }
    }
}
