//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.tags = new HashSet<Tag>();
        }
    
        public int id_post { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string shorDescription { get; set; }
        public string body { get; set; }
        public Nullable<int> id_author { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual Author author { get; set; }
        public virtual Category category { get; set; }
        public virtual ICollection<Tag> tags { get; set; }
    }
}
